#!/system/bin/sh

dcrypt(){

if [ ! -e /sdcard/resolvername ]; then 
		echo " " > /sdcard/resolvername; 
fi
if [ "`cat /sdcard/resolvername`" = " " ];then 
		RESOLVER_NAME=dnscrypt.eu-dk
else
		RESOLVER_NAME="`cat /sdcard/resolvername`"
fi
if [ -e "/sdcard/dnscrypt-resolvers.csv" ];then
				RESOLVER_LIST="/sdcard/dnscrypt-resolvers.csv"
				else
				RESOLVER_LIST="/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv"
fi
dnscrypt-proxy \
--daemonize \
--resolver-name="$RESOLVER_NAME" \
--resolvers-list="$RESOLVER_LIST" && \
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1 && \
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
}

if [ "x${1}" = "xenable" -o "x${1}" = "xENABLE" ]; then
        echo "Enabling dnscrypt-proxy..."
        iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
        iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
        ps ax | grep 'dnscrypt-proxy' | while read pid _; do kill "$pid" ; done
       dcrypt
        echo "Done"
        exit
elif [ "x${1}" = "xdisable" -o "x${1}" = "xDISABLE" ]; then
        echo "Disabling dnscrypt-proxy..."
        iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
        iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
        ps ax | grep 'dnscrypt-proxy' | while read pid _; do kill "$pid" ; done
        echo "Done"
        exit
elif [ "x${1}" = "xupdate" -o "x${1}" = "xUPDATE" ]; then
echo "Updating resolver list..."
check=$?
curl -s -k https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv -o /sdcard/dnscrypt-resolvers.csv
if [ "$check" != "0" ];then curl -s -C - -o /sdcard/dnscrypt-resolvers.csv -k https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv --retry 20
fi
echo "Done..."
	exit
else
        echo "This script allows you to enable & disable dnscrypt-proxy"
        echo "And update resolver list"
        echo
        echo "Usage:"
        echo "enable    -    Enable dnscrypt"
        echo "disable   -    Disable dnscrypt"
        echo "update    -    Update Resolver"
        echo "manually set resolver : "
        echo "echo 	\"resolver-name\" > /sdcard/resolvername "
        echo
fi
